spring.data.mogodb.host = localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
# if there's username and password for authentication
# spring.data.mongodb.username = xyz
# spring.data.mongodb.password = abc
spring.data.mongodb.auto-index-creation=true
# Enables index creation in mongodb automatically