spring.data.mongodb.uri=mongodb+srv://dbMilind:milimongo@cluster0.pp151ey.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
# if there's username and password for authentication
# spring.data.mongodb.username = xyz
# spring.data.mongodb.password = abc
spring.data.mongodb.auto-index-creation=true
# Enables index creation in mongodb automatically
spring.main.allow-circular-references=true