spring.data.mongodb.uri=${MongoURL}
spring.data.mongodb.database=journaldb
# if there's username and password for authentication
# spring.data.mongodb.username = xyz
# spring.data.mongodb.password = abc
spring.data.mongodb.auto-index-creation=true
# Enables index creation in mongodb automatically
spring.main.allow-circular-references=true
